volumes:
  mssql_data:

  scraper_data:


services:
  webapp:
    image: vendingmanager
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=VendingDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=America/Santiago
      # URL del servicio de scraping para que .NET sepa a dónde llamar
      - ScraperServiceUrl=http://scraper:8000
    depends_on:
      - db
      - scraper

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - TZ=America/Santiago
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"

  # Nuevo servicio para el Scraper (Python + Playwright)
  scraper:
    build:
      context: ./services/scraper
      dockerfile: Dockerfile
    volumes:
      - scraper_data:/app/downloads
    ports:
      - "8000:8000" # Opcional: solo para pruebas locales, interno no hace falta exponerlo
    environment:
      - TZ=America/Santiago
      - OURVEND_USER=${OURVEND_USER}
      - OURVEND_PASS=${OURVEND_PASS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
