version: '3.8'

volumes:
  mssql_data_dev:
  scraper_data_dev:


services:
  webapp-dev:
    image: vendingmanager-dev
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db-dev;Database=VendingDB_Dev;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=America/Santiago
      - ScraperServiceUrl=http://scraper-dev:8000
    depends_on:
      - db-dev
      - scraper-dev

  db-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - TZ=America/Santiago
    volumes:
      - mssql_data_dev:/var/opt/mssql
    ports:
      - "1434:1433"

  scraper-dev:
    build:
      context: ./services/scraper
      dockerfile: Dockerfile
    volumes:
      - scraper_data_dev:/app/downloads
    ports:
      - "8001:8000"
    environment:
      - TZ=America/Santiago
      - OURVEND_USER=${OURVEND_USER}
      - OURVEND_PASS=${OURVEND_PASS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
